[ble]
name = "Rustboard"
split = true

[matrix]
# rows = 4
# cols = 5
# To be implemented: pins parsing
row_pins = ['P0_17', 'P0_20', 'P0_22', 'P0_22']
col_pins = ['P0_31', 'P0_29', 'P0_02', 'P1_15', 'P1_15']

[debounce]
key_debounce = 10 # in ms

[keymap]
layers = 2
# To be implemented: keymap layout parsing
# keymap = []
